-- Backfill cohorts that have no invite_pin with a generated 8-char code.
-- New cohorts will have invite_pin generated by the API on creation.

DO $$
DECLARE
  rec RECORD;
  chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  code TEXT;
  ok BOOLEAN;
BEGIN
  FOR rec IN SELECT id FROM public.cohorts WHERE invite_pin IS NULL LOOP
    LOOP
      -- Generate an 8-char random code from the allowed charset
      code := '';
      FOR i IN 1..8 LOOP
        code := code || substr(chars, floor(random() * length(chars) + 1)::int, 1);
      END LOOP;
      -- Check uniqueness before assigning
      SELECT NOT EXISTS (
        SELECT 1 FROM public.cohorts WHERE invite_pin = code
      ) INTO ok;
      EXIT WHEN ok;
    END LOOP;
    UPDATE public.cohorts SET invite_pin = code WHERE id = rec.id;
  END LOOP;
END;
$$;
